### ISSUE TITLE
Dart / flutter supprt

### ISSUE THREAD

**Issue by gedw99** [uptrace/roadmap#13]
Uptrace would be great for dart flutter.

Otel is protobuf based and dart / flutter has good support for protobuf and GRPC . I use it with golang backend all all projects.

So I think it’s possible to add dart support without boiling the ocean.

currenty I use Debye but I prefer uptrace any day of the week :)

**Comment by vmihailenco** [comment]
Hello,

>So I think it’s possible to add dart support without boiling the ocean.

I assume you mean errors monitoring? Because from what I've seen so far tracing in browsers looks pathetic. But probably I've looked at wrong examples - please share the good ones :)

As for the errors monitoring - yes, we would like to support Dart & Flutter. I wonder if using JS with Dart+Flutter is still a viable option? Is there anything specific to Dart+Flutter (like sourcemaps)?

>currenty I use Debye

Do you have a link or a screenshot of the functionality you are looking for? I was not able to find any info on Debye :)

**Comment by gedw99** [comment]
Hey
Sorry missed this.

you don’t need to trace the browser. You can use middleware in your dart code to call uptrace. Typically that’s GRPC / protobuf and other roc tech.

does that help ?

**Comment by gedw99** [comment]
See this issue 

https://github.com/open-telemetry/community/issues/552

**Comment by vmihailenco** [comment]
Please open an issue in https://github.com/uptrace/cloud-changelog if you are interested.
